### ISSUE TITLE
No style of the header of the markdown app

### ISSUE THREAD

**Issue by Narven** [adam-lynch/developing-an-electron-edge#3]
In the 

``` css
body {
  margin: 0;
  padding: 0;
  font-family: sans-serif;
}

.container {
  width: 100%;
  height: 100vh;
  display: block;
}

.editor,
.preview {
  box-sizing: border-box;
  padding: 10px;
}

.editor {
  width: 50%;
  height: 100%;
  float: left;
}

.editor textarea {
  resize: none;
  border: none;
  outline: none;
  width: 100%;
  height: 100%;
}

.preview {
  width: 50%;
  height: 100%;
  float: left;
  padding-left: 2px;
  margin-left: -2px;
  background-color: #ddd;
}
```

In this css code there's nothing to apply some `background-color` to the `header`

Probably missing:

``` css
.header {
    background-color: #52381E;
}
```
